#!/bin/bash

faceunlock_startService='    invoke-static {}, Lax/nd/faceunlock/FaceUnlockService;->startService()V'

faceunlock_setEnrollSurface() {
    local reg=$1
    faceunlock_setEnrollSurface="    invoke-static/range {${reg} .. ${reg}}, Lax/nd/faceunlock/FaceUnlockService;->setEnrollSurface(Landroid/view/Surface;)V"
}