#!/bin/bash
dirnow=$PWD
source $dirnow/faceunlock/patch
debug=false
if [[ -f $dirnow/.debug ]]; then
    debug=true
fi

apkeditor() {
    jarfile=$dirnow/tool/APKEditor.jar
    javaOpts="-Xmx4096M -Dfile.encoding=utf-8 -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true"

    java $javaOpts -jar "$jarfile" "$@"
}

expressions_fix() {
	var=$1
	escaped_var=$(printf '%s\n' "$var" | sed 's/[\/&]/\\&/g')
	escaped_var=$(printf '%s\n' "$escaped_var" | sed 's/\[/\\[/g' | sed 's/\]/\\]/g' | sed 's/\./\\./g' | sed 's/;/\\;/g')
	echo $escaped_var
}

patchservices() {
    jarname=$1

    echo "Decompiling ${jarname}..."
    if [[ $debug == false ]]; then
        apkeditor d -i $jarname -o tmp_jar > /dev/null 2>&1
    elif [[ $debug == true ]]; then
        apkeditor d -i $jarname -o tmp_jar
    fi
    mv $jarname tmp.jar

    echo "Patching ${jarname}..."

    local faceProviderclassfile=$(find tmp_jar/ -name 'FaceProvider.smali' -printf '%P\n')
	local faceSvcclassfile=$(find tmp_jar/ -name 'FaceService.smali' -printf '%P\n')

    local faceSvcclassfile=$(find tmp_jar/ -name 'FaceService.smali' -printf '%P\n')
    local onStartMethod=$(expressions_fix "$(grep ' onStart()V' tmp_jar/$faceSvcclassfile)")

	sed -n "/^${onStartMethod}/,/^\.end method/p" tmp_jar/$faceSvcclassfile > onStart_tmp
	sed -i "/^${onStartMethod}/,/^\.end method/d" tmp_jar/$faceSvcclassfile

	awk -v h="$faceunlock_startService" '/return-void/ {print h} {print}' onStart_tmp >> tmp_jar/$faceSvcclassfile
	rm -rf onStart_tmp
	
	# OPTIONAL
	local faceProviderclassfile=$(find tmp_jar/ -name 'FaceProvider.smali' -printf '%P\n')
	local schedEnrollMethod=$(expressions_fix "$(grep ' scheduleEnroll(IL' tmp_jar/$faceProviderclassfile)")
	if [[ $schedEnrollMethod != "" ]]; then
		sed -n "/^${schedEnrollMethod}/,/^\.end method/p" tmp_jar/$faceProviderclassfile > schedEnroll_tmp
		sed -i "/^${schedEnrollMethod}/,/^\.end method/d" tmp_jar/$faceProviderclassfile

		local prevSurfaceReg=$(grep ', "previewSurface"' schedEnroll_tmp | awk '{print $2}' | tr -d ",")
		if [[ $prevSurfaceReg != "" ]]; then
			faceunlock_setEnrollSurface $prevSurfaceReg
			awk -v h="$faceunlock_setEnrollSurface" '/^\.method/ {m=1; inj=0; print; next} m && !inj {if ($0 ~ /^[ \t]*(\.locals|\.registers|\.param|#|$)/) {print; next} else {print h; inj=1; print; next}} 1' schedEnroll_tmp >> tmp_jar/$faceProviderclassfile
		else
			echo "Skipping optional faceunlock enroll preview patch because there's no readable previewSurface register!"
		fi
		rm -rf schedEnroll_tmp
	else
		echo "Skipping optional faceunlock enroll preview patch because there's no scheduleEnroll method!"
	fi
    echo "Compiling ${jarname} classes.."
    if [[ $debug == false ]]; then
        apkeditor b -i tmp_jar > /dev/null 2>&1
    elif [[ $debug == true ]]; then
        apkeditor b -i tmp_jar
    fi
    unzip tmp_jar_out.apk 'classes*.dex' -d tmp_jar > /dev/null 2>&1

    rm -rf tmp_jar/.cache
    local patchclass=$(expr $(find tmp_jar/ -type f -name '*.dex' | wc -l) + 1)
    cp faceunlock/classes.dex tmp_jar/classes${patchclass}.dex

    cd tmp_jar
    echo "Zipping classes..."
    zip -qr0 -t 07302003 $dirnow/tmp.jar classes*
    cd $dirnow
    echo "Zipaligning ${jarname}..."
    zipalign -v 4 tmp.jar $jarname > /dev/null
    rm -rf tmp.jar tmp_jar tmp_jar_out.apk
    echo "Done!"
}

usage() {
    echo "Usage: $0 [service.jar file]"
    echo ""
    echo 'Create a file named ".debug" in current dir to show all logs'
    exit 1
}

if [[ $1 == "" ]]; then
    usage
    exit 1
fi

patchservices $1
